feat: core-api add public key api
TencentBlueKing/blueking-apigateway pull request #390
Opened 2023-12-05 12:44 UTC by Han-Ya-Jun

### Description
迁移dashboard public key api 至 core-api，完全兼容历史接口

Fixes # (issue)

### Checklist

- [ -] 填写 PR 描述及相关 issue (write PR description and related issue)
- [- ] 代码风格检查通过 (code style check passed)
- [- ] PR 中包含单元测试 (include unit test)
- [- ] 单元测试通过 (unit test passed)
- [- ] 本地开发联调环境验证通过 (local development environment verification passed)

2023-12-05 12:57 UTC, alex-smile commented on src/core-api/pkg/api/microgateway/public_key.go
> +	//        "public_key": ""
还有一个 issuer

<img width="589" alt="image" src="https://github.com/TencentBlueKing/blueking-apigateway/assets/17827133/54429380-eae0-46cc-848e-02aeed45b792">

2023-12-06 01:18 UTC, alex-smile commented on src/core-api/pkg/api/microgateway/public_key.go
> +	BkGatewayName string `uri:"api_name" example:"gateway"`
如果是 url 里面的位置参数，不需要与原来的 key 一致，应为请求时并没有指定 key，这里就可以用 gateway_name 了？

2023-12-06 02:36 UTC, zhu327 commented on src/core-api/pkg/api/microgateway/public_key.go
> +type queryPublicKeyFromOpenSerializer struct {
名字的后缀 FromOpen 有点不合适, 应该明确是FromOpenXX

2023-12-06 02:36 UTC, zhu327 commented on src/core-api/pkg/api/microgateway/public_key.go
> +	// query params: bk_gateway_name or api_name
同上命名改下

2023-12-06 02:36 UTC, zhu327 commented on src/core-api/pkg/api/microgateway/public_key.go
> +		util.BadRequestErrorJSONResponse(c, "api_name is required")
gateway_name

2023-12-06 02:36 UTC, zhu327 commented on src/core-api/pkg/service/public_key.go
> +	GetByGatewayName(ctx context.Context, gatewayName string) (string, error)
同上改下ApiGateway命名

2023-12-06 02:36 UTC, zhu327 commented on src/core-api/pkg/middleware/bk_gateway_jwt.go
> +func getBkGatewayPublicKey(ctx context.Context) (string, error) {
这里的函数与下面Service的方法重复了?

2023-12-06 03:01 UTC, Han-Ya-Jun commented on src/core-api/pkg/api/microgateway/public_key.go
> +	// query params: bk_gateway_name or api_name
done

2023-12-06 03:06 UTC, wklken requested changes

2023-12-06 06:24 UTC, wklken commented on src/core-api/pkg/middleware/bk_gateway_jwt.go
> +		token, err := jwt.Parse(signedToken, func(token *jwt.Token) (interface{}, error) {
之前权限中心的处理方式: https://github.com/TencentBlueKing/bk-iam/blob/7137ffab005c011064aea0069182e0797e12e43f/pkg/middleware/client_jwt.go#L65

2023-12-06 07:21 UTC, Han-Ya-Jun commented on src/core-api/pkg/api/microgateway/public_key.go
> +	//        "public_key": ""
done

2023-12-06 09:18 UTC, Han-Ya-Jun commented on src/core-api/pkg/middleware/bk_gateway_jwt.go
> +	BkAPIGatewayName      = "bk-apigateway"
done

2023-12-06 09:19 UTC, Han-Ya-Jun commented on src/core-api/pkg/api/microgateway/public_key.go
> +	BkGatewayName string `uri:"api_name" example:"gateway"`
done

2023-12-06 09:20 UTC, Han-Ya-Jun commented on src/core-api/pkg/api/microgateway/public_key.go
> +type queryPublicKeyFromOpenSerializer struct {
done, 单独拎出来放到open目录了：`queryPublicKey`

2023-12-06 09:20 UTC, Han-Ya-Jun commented on src/core-api/pkg/api/microgateway/public_key.go
> +		util.BadRequestErrorJSONResponse(c, "api_name is required")
done

2023-12-06 09:31 UTC, Han-Ya-Jun commented on src/core-api/pkg/api/microgateway/public_key.go
> +	gatewayName := query.BkGatewayName
done

2023-12-07 03:26 UTC, Han-Ya-Jun commented on src/core-api/pkg/middleware/bk_gateway_jwt.go
> +		publicKeyString, err := getBkGatewayPublicKey(c.Request.Context())
done

2023-12-07 03:26 UTC, Han-Ya-Jun commented on src/core-api/pkg/api/microgateway/public_key.go
> +		util.BadRequestErrorJSONResponse(c, "api_name is required")
done

2023-12-07 03:27 UTC, Han-Ya-Jun commented on src/core-api/pkg/middleware/bk_gateway_jwt.go
> +func getBkGatewayPublicKey(ctx context.Context) (string, error) {
done, 已复用

2023-12-07 03:27 UTC, Han-Ya-Jun commented on src/core-api/pkg/api/microgateway/public_key.go
> +}
done

2023-12-07 03:28 UTC, Han-Ya-Jun commented on src/core-api/pkg/middleware/bk_gateway_jwt.go
> +			util.UnauthorizedJSONResponse(c, "no authorization credentials provided")
done

2023-12-07 03:28 UTC, Han-Ya-Jun commented on src/core-api/pkg/server/router.go
> +	// bk_api_gateway open api
done

2023-12-07 03:29 UTC, Han-Ya-Jun commented on src/core-api/pkg/middleware/bk_gateway_jwt.go
> +		token, err := jwt.Parse(signedToken, func(token *jwt.Token) (interface{}, error) {
done 解析校验部分参照了iam的

2023-12-07 03:30 UTC, Han-Ya-Jun commented on src/core-api/pkg/service/public_key.go
> +	GetByGatewayName(ctx context.Context, gatewayName string) (string, error)
和core-api service层的先保持一致了

2023-12-07 03:50 UTC, wklken commented
PR 合并到master, 1.12 不用着急上这个接口

2023-12-07 03:51 UTC, wklken commented on src/core-api/pkg/api/open/public_key.go
> +}
写两个, V1/V2, 不要在下层做兼容(dashboard那么做是因为迫不得已)

2023-12-07 03:59 UTC, wklken commented on src/core-api/pkg/api/open/public_key.go
> +		"issuer":     config.GlobalConfig.OpenAPI.BkAPIGatewayJwtIssuer,
这个不是从jwt中解开的么?

2023-12-07 03:59 UTC, wklken commented on src/core-api/pkg/middleware/bk_gateway_jwt.go
> +	}
判断到这里就可以了 => 这里后面不需要用到app_code, 不用取/判断

2023-12-07 03:59 UTC, wklken commented on src/core-api/pkg/middleware/bk_gateway_jwt.go
> +		err = verifyClientID(signedToken, []byte(publicKeyString))
- verifyClientID 名字改一下, 这里是校验 jwt 合法

2023-12-07 03:59 UTC, wklken commented on src/core-api/pkg/middleware/bk_gateway_jwt.go
> +func BkGatewayJWTAuthMiddleware() func(c *gin.Context) {
这里也变成 2 个middleware

2023-12-08 06:20 UTC, closed without merging